- name: create a harvester directory
  become: yes
  file:
    path: "{{ workplace_directory }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775

#- name: attach github key
#  become: yes
#  template:
#    src: "../templates/GroupKey"
#    dest: "/home/ubuntu/.ssh/GroupKey"
#    owner: ubuntu
#    group: ubuntu
#    mode: 0600


- name: clone code to Server
  git:
    force: yes
    repo: "https://{{github_user}}:{{github_pass}}@github.com/Jeremypan/CCC_Assignment_2.git"
    dest: "{{ workplace_directory }}"
    version: "{{ branch }}"

- name: upload aurin json data to couchdb/updateview
  become: yes
  shell: 'nohup python3 /home/ubuntu/CCC/aurin_sa4/aurin.py'
  when: inventory_hostname == ip_address_list[1]
  # upload data run aurin.py