- set_fact:
    ip_address_list: '{{ node_ips.split(",") }}'
    cacheable: yes

- name: pull nginx nginx_image
  become: yes
  docker_image:
    name: nginx
    source: pull
    state: present

- name: copy files
  become: yes
  template:
    src: "../templates/nginx.conf"
    dest: '/home/ubuntu/nginx.conf'
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=rwx,o=rwx


- name: create container nginx
  become: yes
  docker_container:
    state: started
    name: nginx
    image: nginx
    detach: yes
    ports:
      - "8080:80"
    volumes:
      /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf:rw


