- name: install essenstails for web
  tags: always
  become: yes
  pip:
    name: ['flask']
    state: latest

- name: copy webconfig
  become: yes
  template:
  src: "../templates/web_config.py"
  dest: "/home/ubuntu/CCC/src/Web/web_config.py"
  owner: ubuntu
  group: ubuntu
  mode: 0600

- name: launch flask web
  become: yes
  command: "nohup python3 /home/ubuntu/CCC/src/Web/app.py"

