---
- hosts: localhost
  vars_files:
    - host_vars/local_vars.yaml
  gather_facts: true

  roles:
    - role: common
    - role: images
    - role: volumes
    - role: security-group
    - role: create_instance
