

- name: Get infos on container
  become: yes
  docker_container_info:
    name: couchdb3_{{ inventory_hostname }}
  register: result
  ignore_errors: yes

- name: Does container exist_No
  set_fact:
    container_result: True
  when: result.failed

- name: Does container exist_Yes
  set_fact:
    container_result: False
  when: not result.failed

- name: debug
  debug:
    msg: '{{ container_result }}'

- name: Uninstall old versions of docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io','docker-compose']
    state: absent
  when: container_result

- name: Install dependencies
  tags: 'docker'
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'python-setuptools', 'software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes
  when: container_result

- name: Add Docker apt repository key
  tags: 'docker'
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: container_result

- name: Add Docker apt repository and update apt cache
  tags: 'docker'
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present
  when: container_result

- name: Install docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes
  when: container_result

- name: Install docker-compose
  tags: 'docker'
  become: yes
  pip:
    name: ['docker-compose']
    version: 1.25.5
    state: present
  when: container_result
    

- name: Check Directory if it exists
  become: yes
  stat:
    path: '/etc/systemd/system/docker.service.d'
  register: docker_service_dir
  when: container_result

- name: Create directory
  become: yes
  file:
    path: '/etc/systemd/system/docker.service.d'
    state: directory
  when: container_result

- name: Check file if it exists
  become: yes
  stat:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
  register: http_proxy_conf

- name: Touch docker-config
  become: yes
  file: 
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    state: touch
    mode: u=rwx,g=rwx,o=rwx
  when: container_result

- name: Add Proxy in /etc/systemd/system/docker.service.d/http-proxy.conf
  become: yes
  lineinfile:
    line: "[Service]\nEnvironment=\"HTTP_PROXY={{ proxy_address }}\""
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  when: container_result
  
    
- name: Reboot Docker_1_step
  become: yes
  command: systemctl daemon-reload
  when: container_result

- name: Reboot Docker_2_step
  become: yes
  command: systemctl restart docker
  when: container_result