---
- name: Uninstall old versions of docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io','docker-compose']
    state: absent

- name: Install dependencies
  tags: 'docker'
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'python-setuptools', 'software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add Docker apt repository key
  tags: 'docker'
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository and update apt cache
  tags: 'docker'
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  tags: 'docker'
  become: yes
  pip:
    name: ['docker-compose']
    version: 1.22.0
    state: present
    

- name: Check Directory if it exists
  become: yes
  stat:
    path: '/etc/systemd/system/docker.service.d'
  register: docker_service_dir

- name: Create directory
  become: yes
  file:
    path: '/etc/systemd/system/docker.service.d'
    recurse: yes
    state: directory
  when: docker_service_dir.stat.exists == false

- name: Check file if it exists
  become: yes
  stat:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
  register: http_proxy_conf

- name: Touch docker-config
  become: yes
  file: 
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    state: touch
    mode: u=rwx,g=rwx,o=rwx
  when: http_proxy_conf.stat.exists == false

- name: Add Proxy in /etc/systemd/system/docker.service.d/http-proxy.conf
  become: yes
  lineinfile:
    line: "[Service]\nEnvironment=\"HTTP_PROXY={{ proxy_address }}\""
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    
- name: Reboot Docker_1_step
  become: yes
  command: systemctl daemon-reload

- name: Reboot Docker_2_step
  become: yes
  command: systemctl restart docker 